title: Seiya Kobayashi
tagline: >
  Seiya Kobayashi's engineering blog. 小林聖弥の技術系ブログ。
description: >
  Seiya Kobayashi's engineering blog. Blog posts cover a wide range topics, including, but not limited to, AI, blockchains, applied cryptography, Ethereum, and ZKP (Zero-Knowledge Proof).
  小林聖弥の技術系ブログ。取り扱うブログトピックは、AI・ブロックチェーン・応用暗号技術・イーサリアム・ゼロ知識証明と多岐に及ぶ。
url: https://blog.seiya.work/
author:
  name: Seiya Kobayashi | 小林 聖弥
  email: eng@seiya.work
twitter:
  username: seiya_tech
locale: ja_JP
remote_theme: jekyll/minima
plugins:
  - jekyll-seo-tag
  - jekyll-latex
github: [metadata]
header_pages:
  - about.md
show_excerpts: false
minima:
  skin: classic
  date_format: "%Y-%m-%d"
  social_links:
   - { platform: telegram, user_url: "https://t.me/seiya_kobayashi" }
   - { platform: facebook, user_url: "https://www.facebook.com/seiya.kb" }
