title: Seiya Kobayashi
tagline: >
  Seiya Kobayashi's engineering blog
description: >
  Blog posts cover a wide range of topics; from AI to blockchain to applied cryptography.
url: https://blog.seiya.work/
author:
  name: Seiya Kobayashi | 小林 聖弥
  email: eng@seiya.work
twitter:
  username: seiya_tech
locale: ja_JP
remote_theme: jekyll/minima
plugins:
  - jekyll-seo-tag
  - jekyll-latex
github: [metadata]
header_pages:
  - about.md
show_excerpts: false
minima:
  skin: classic
  date_format: "%Y-%m-%d"
  social_links:
   - { platform: telegram, user_url: "https://t.me/seiya_kobayashi" }
   - { platform: facebook, user_url: "https://www.facebook.com/seiya.kb" }
